# Generated by Django 3.0.7 on 2020-07-08 02:24

import blog.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181117_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pengarang',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100, validators=[blog.validators.validate_author]),
        ),
    ]
