# Generated by Django 3.0.7 on 2020-07-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_jenis_kelamin'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
