# Generated by Django 3.0.7 on 2020-07-05 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='email',
            field=models.EmailField(default='yogi@admin.com', max_length=254),
        ),
    ]
